# Generated by Django 3.2 on 2022-04-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20220401_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='price_electronic',
        ),
        migrations.AddField(
            model_name='book',
            name='price_hardcover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='price_paperback',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=6),
            preserve_default=False,
        ),
    ]
