# Generated by Django 3.2 on 2022-04-03 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20220401_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='sub_category',
            options={'verbose_name_plural': 'Sub_Categories'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_type',
        ),
        migrations.AddField(
            model_name='book',
            name='book_type1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type1', to='books.type'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type2', to='books.type'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_type3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type3', to='books.type'),
        ),
    ]
